name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: macos-latest
          platform: darwin
          arch: x64
        - os: windows-latest
          platform: win32
          arch: x64
    timeout-minutes: 5
    steps:
      - uses: holepunchto/actions/.github/steps/setup-repo@v1
      - run: npm i -g bare-runtime@latest
      - run: npm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm t
      - run: npm run lint
